# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdc23e30d4fa2cd08d0dd90a47b0a8c8a594c3f3e85a1f35b32441a417d35053dd40fefe9b785ea9575d8f98f2c62fe3865b571c63566c4613bb4b2f7bc8a97e

test:
  secret_key_base: 9ed44b049779429240222038955e52b2276496c939bd5d8e92513f23cb4e23fac542fc3477cc4eaf30f33b555bbdad224b4fa72f8918ab218448d2fef7c884bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
